### PR TITLE
add ids to all tiles

### PR DESCRIPTION
**Pull request by scytacki**
these were added using the script in CLUE
add-ids-to-tiles.ts

### CODE REVIEW

**Comment by scytacki** [comment]
@tejal-shah and @lbondaryk this is a PR for testing the effects of adding ids to all of the tiles in the curriculum.

The plan is:
- test to make sure all of the units load in this branch
- test to see what it looks like if we tried to merge this into the active authoring branches
- if all that looks good, then in the evening add all of the ids to main and update the active authoring branches

Given the other plan to start new authoring branches we'll have to figure out how to sequence these two plans.

**Comment by scytacki** [comment]
I loaded each of the units using this URL format:
https://collaborative-learning.concord.org/branch/master/?appMode=dev&unit=https://models-resources.concord.org/clue-curriculum/branch/add-ids-to-all-tiles/twmm/content.json

I only checked the default problem of each unit. This at least makes sure the JSON of the unit is still valid. It'd be better if we checked every single problem, but I personally wouldn't do that with automation.

**Comment by tejal-shah** [comment]
@scytacki , I'll check this today. Can you please let me know if it's enough to make sure that every problem loads ok? Or would it make more sense to check if all the tiles in each problem load?

**Comment by scytacki** [comment]
If you can check each problem that'd be great. The tiles that would be the most likely to fail are things with datasets. Tables, graphs, and data cards. I'll search the changes to find a few myself. I think if one works they all should work. Also it could save you time if you look at the changes to see which sections/problems were modified. Not all were.

**Comment by scytacki** [comment]
I looked through the changes. I couldn't find any places where there are tiles using datasets that were changed. This makes sense since any tile using a dataset needs an id, so it shouldn't be changed by the script.

If you want to look at some example of sections with datasets that were modified. I only found:
- example-shared-data/investigation-1/problem-1/taska/content.json
There might be more, but I'd need to do more of a script to track them down.

There are several sections with Tables that were modified, but these are old sections that weren't using datasets yet. Here are some examples:
- moth-few/investigation-1/problem-1/fieldNotes/content.json
- cas/investigation-2/problem-1/whatIf/content.json

**Comment by lbondaryk** [comment]
I had thought that this work was run on main, and that when I did a botched merge from CMPAuthor it wiped out these changes, specifically in the Stretching and Shrinking unit (SAS, the default) restoring them to their incorrect document_Table_1 form. So I reverted, thinking I had wiped out all of Scott's changes. If that's not true I can just fix those two IDs on my branch and remerge.

**Comment by scytacki** [comment]
@tejal-shah,  @lbondaryk  would like to get this applied to main as soon as possible so that fewer comments left by teachers on curriculum tiles get lost. I'm going to try to do it tonight, but I will at least do a test merge of the changes in the NewCMPAuthor branch, the MothAuth, and the modsAuth branches. If those merges go relatively cleanly I'll just go ahead and apply this to main and those branches.  If the merges don't go cleanly we might have to wait one more day for me to sort that out.

**Comment by tejal-shah** [comment]
@scytacki , sure, please go ahead. I checked the first few units and I can continue checking the rest after it is merged. I haven't found any issues in the units (bio, brain, cas, cr, dfe)  I've checked so far.

**Pull request closed without merging**
